Repository snu-quiqcl/qiwis, pull requests merged in 2023-07, with the labels that each got.

#195 Logger app using `logging`
  .github/workflows/unittest.yml
  examples/logger.py
Labels: enhancement

#203 Add code owners
  .github/CODEOWNERS
Labels: repository

#201 Aijuh/199/log level selector
  examples/logger.py
Labels: enhancement

#198 Becatrue/187/config json
  .github/workflows/unittest.yml
  README.md
  examples/config.json
  qiwis.py
  test.py
Labels: enhancement

#209 Remove Python 3.7 from the GitHub actions and add 3.11
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  setup.py
Labels: repository

#207 Handle re-creating the existing app
  .github/workflows/unittest.yml
  qiwis.py
  test.py
Labels: bug, test
