Repository snu-quiqcl/qiwis, pull requests merged in 2023-03, with the labels that each got.

#63 Create setup file
  .gitignore
  setup.py
Labels: documentation

#71 Becatrue/66/reorganize swift
  swift/swift.py
Labels: enhancement

#87 Update README.md and write Wiki
  README.md
Labels: documentation

#91 Set a central widget in the mainWindow
  swift/swift.py
Labels: enhancement

#81 Becatrue/77/logging
  apps/datacalc.py
  apps/dbmgr.py
  apps/numgen.py
  apps/poller.py
  swift/swift.py
Labels: enhancement, example

#93 Update README.md
  README.md
Labels: documentation

#96 Fix the error that the bus thread is not quited
  swift/bus.py
Labels: bug

#80 Improved handling of app and bus information introducing dataclasses `AppInfo` and `BusInfo`
  setup.json
  swift/swift.py
Labels: enhancement, refactor

#100 Becatrue/88/init test
  .gitignore
  tests/test_swift.py
Labels: test

#103 Type hints
  apps/backend.py
  apps/datacalc.py
  apps/dbmgr.py
  apps/logger.py
  apps/numgen.py
  apps/poller.py
  swift/app.py
  swift/bus.py
Labels: enhancement, refactor, style

#106 Change apps to examples and move setup.json
  examples/backend.py
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/numgen.py
  examples/poller.py
  examples/setup.json
Labels: example, repository

#105 Becatrue/101/unittest action
  .github/workflows/unittest.yml
  README.md
Labels: test, repository

#108 Add Python 3.7 runner for Pylint
  .github/workflows/pylint.yml
Labels: repository

#109 `parent` parameter order to the last
  examples/datacalc.py
  examples/dbmgr.py
  examples/numgen.py
  examples/poller.py
  swift/bus.py
Labels: refactor, style

#112 Kangz12345/110/replace bus with queued connection
  examples/setup.json
  swift/bus.py
  swift/swift.py
Labels: enhancement, refactor

#116 Remove statements about sys.modules in _add_to_path()
  swift/swift.py
Labels: refactor

#117 Update to make GitHub Action simpler
  .coveragerc
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  .pylintrc
Labels: repository

#122 Test swift.swift
  .github/workflows/pylint.yml
  swift/swift.py
  tests/.pylintrc
  tests/test_swift.py
Labels: test

#124 Fix a duplicated called bug in pollor
  examples/poller.py
Labels: bug

#125 Rebase develop to main
  README.md
Labels: repository
