Repository snu-quiqcl/qiwis, pull requests merged in 2023-11, with the labels that each got.

#238 Support for frame title
  .github/workflows/unittest.yml
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/numgen.py
  examples/poller.py
  qiwis.py
  test.py
Labels: enhancement, test, example

#240 Add `trust` opt in app info to bypass checking permission
  examples/config.json
  qiwis.py
  test.py
Labels: enhancement

#241 Update version to 3.0.0
  README.md
  setup.py
Labels: repository

#242 Merge to release branch for new version 3.0.0
  .github/workflows/unittest.yml
  README.md
  examples/config.json
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/numgen.py
  examples/poller.py
  qiwis.py
  setup.py
  test.py
Labels: repository

#244 Fix the bug that shows frame titles incorrectly
  README.md
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/poller.py
  qiwis.py
  setup.py
Labels: bug, example, repository

#245 Release v3.0.1
  README.md
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/poller.py
  qiwis.py
  setup.py
Labels: repository
