Repository snu-quiqcl/qiwis, pull requests merged in 2023-09, with the labels that each got.

#213 Support a central widget
  examples/dbmgr.py
  qiwis.py
  test.py
Labels: enhancement

#214 Add the logo as icon and background
  examples/config.json
  qiwis.py
  resources/background.jpg
  resources/icon.jpg
Labels: enhancement

#216 Update `self.appInfos` in `create/destroyApp()`
  qiwis.py
Labels: bug

#217 Fix `constants` to work properly for created apps
  qiwis.py
Labels: bug

#218 Update README.md and setup.py for v2.1.0 release
  README.md
  setup.py
Labels: repository

#219 Release for v2.1.0
  .github/CODEOWNERS
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  .pylintrc
  .pylintrc_test
  README.md
  examples/backend.py
  examples/config.json
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/numgen.py
  examples/poller.py
  qiwis.py
  resources/background.jpg
  resources/icon.jpg
  setup.py
  test.py
Labels: repository

#222 Enable the central widget, `MdiArea` scrolled
  qiwis.py
Labels: enhancement

#224 Update the version in `setup.py` and `README.md`
  README.md
  setup.py
Labels: repository

#225 Release v2.1.1
  README.md
  qiwis.py
  setup.py
Labels: repository

#227 Remove show option & Support floating area
  examples/config.json
  examples/dbmgr.py
  qiwis.py
  test.py
Labels: enhancement

#229 Update version to 2.2.0
  README.md
  setup.py
Labels: repository

#230 Merge `develop` to `release` branch
  README.md
  examples/config.json
  examples/dbmgr.py
  qiwis.py
  setup.py
  test.py
Labels: repository
