Repository snu-quiqcl/qiwis, pull requests merged in 2023-05, with the labels that each got.

#158 Implement several examples for swift-call
  examples/dbmgr.py
  examples/numgen.py
  examples/setup.json
Labels: example

#160 Fix the bug about the type of Swift._subscribers
  swift.py
Labels: bug

#161 Testing for updated parts
  .github/workflows/pylint.yml
  .github/workflows/unittest.yml
  .pylintrc_test
  swift.py
  test.py
  tests/test_swift.py
Labels: test

#163 Testing swift-call-related codes
  swift.py
  test.py
Labels: bug, test

#166 Change `swift` to `qiwi`
  .pylintrc_test
  README.md
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/numgen.py
  examples/poller.py
  qiwi.py
  setup.py
  test.py
Labels: repository

#168 Rename the project name to `qiwis`
  .coveragerc
  .pylintrc_test
  README.md
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/numgen.py
  examples/poller.py
  qiwis.py
  setup.py
  test.py
Labels: repository

#171 Fix typo in README: git_https
  README.md
Labels: bug, repository

#172 Merging `develop` branch to `main` branch
  README.md
Labels: bug, repository

#173 Preparation for release v2.0.1
  README.md
  setup.py
Labels: bug, repository

#177 Resolve an import error in pip installation using `py_modules`
  README.md
  examples/numgen.py
  setup.py
Labels: bug, repository

#178 Merge for release v2.0.2
  README.md
  examples/numgen.py
  setup.py
Labels: repository
