Repository snu-quiqcl/qiwis, pull requests merged in 2023-04, with the labels that each got.

#127 Becatrue/118/change bus to channel
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/numgen.py
  examples/poller.py
  examples/setup.json
  swift/app.py
  swift/swift.py
  tests/test_swift.py
Labels: refactor

#130 Fix docstring in swift.swift.parse() about indentation
  swift/swift.py
Labels: documentation

#126 Fix all duplicated called bugs
  examples/datacalc.py
  examples/numgen.py
  examples/poller.py
Labels: bug

#129 Implment system request protocol
  swift/app.py
  swift/swift.py
Labels: enhancement

#135 Simplify handling signals in apps
  swift/app.py
Labels: enhancement

#138 Becatrue/132/swift call window
  swift/swift.py
Labels: enhancement

#140 Fix the error not working all original message transfer protocol
  examples/dbmgr.py
  examples/logger.py
  examples/numgen.py
Labels: bug

#141 Swift-call result interface
  swift/app.py
  swift/swift.py
Labels: enhancement

#143 Apply new message transfer protocol to examples
  examples/datacalc.py
  examples/poller.py
Labels: bug

#142 Generalize swift call message protocol
  swift/swift.py
  tests/test_swift.py
Labels: enhancement

#147 Kangz12345/136/simplify swift call request
  swift/app.py
  swift/swift.py
Labels: enhancement

#150 Implement swift-call 'updateFrames()' which updates frames of the app
  swift/swift.py
Labels: enhancement

#154 Add more information to setup.py
  setup.py
Labels: documentation

#155 Add more public API features
  swift/swift.py
Labels: enhancement

#159 Make `swift` be a flat module, not a package
  examples/datacalc.py
  examples/dbmgr.py
  examples/logger.py
  examples/numgen.py
  examples/poller.py
  swift.py
  swift/__init__.py
  swift/app.py
  tests/test_swift.py
Labels: repository
